#pragma once
#define INCORRECT_PARAM_NUMBERS 1
#define CANNOT_START_WSA 2
#define CANNOT_CREATE_SOCKET 3
#define INVALID_IP_ADRESS 4
#define SOCKET_BIND_FAIL 5
#define CANNOT_ALLOCATE_CLIENT_SOCKETS 6
#define CANNOT_ALLOCATE_THREADS 7
#define CANNOT_LISTEN 8